export const SPEECH_IDLE_TIMEOUT_MS = 450;
export const SPEECH_IDLE_POLL_INTERVAL_MS = 16;
export const PREVIOUS_TRACK_SEEK_THRESHOLD_MS = 3000;

export const LESSON_LONG_PRESS_MS = 480;
export const LESSON_AUTO_SCROLL_RESUME_DELAY_MS = 1200;
export const LESSON_AUTO_SCROLL_MIN_INTERVAL_MS = 280;
export const LESSON_AUTO_SCROLL_SAFE_ZONE_RATIO = 0.18;

